// <auto-generated />
using System;
using MedRemind.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedRemind.Core.Migrations
{
    [DbContext(typeof(MedRemindDbContext))]
    partial class MedRemindDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("MedRemind.Core.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoLogoutDays")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FontSize")
                        .HasColumnType("REAL");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SnoozeDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VibrationEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("MedRemind.Core.Models.DoseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MedicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TakenTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId", "ScheduledTime");

                    b.HasIndex("MedicationId", "Status");

                    b.ToTable("DoseLogs");
                });

            modelBuilder.Entity("MedRemind.Core.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FrequencyCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("MedRemind.Core.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiResponse")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PrescriptionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("MedRemind.Core.Models.PrescriptionOCRResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaudeResponse")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComparisonReason")
                        .HasColumnType("TEXT");

                    b.Property<double>("ComparisonScore")
                        .HasColumnType("REAL");

                    b.Property<string>("DoctorName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MedicationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OCRText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OCRTextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenAIResponse")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrescriptionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ProcessingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedProvider")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedResponse")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OCRTextHash");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionOCRResults");
                });

            modelBuilder.Entity("MedRemind.Core.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ReminderTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VoiceRecordingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VoiceRecordingId");

                    b.HasIndex("MedicationId", "IsEnabled");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("MedRemind.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBiometricEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MedRemind.Core.Models.VoiceRecording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VoiceRecordings");
                });

            modelBuilder.Entity("MedRemind.Core.Models.AppSettings", b =>
                {
                    b.HasOne("MedRemind.Core.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("MedRemind.Core.Models.AppSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedRemind.Core.Models.DoseLog", b =>
                {
                    b.HasOne("MedRemind.Core.Models.Medication", "Medication")
                        .WithMany("DoseLogs")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("MedRemind.Core.Models.Medication", b =>
                {
                    b.HasOne("MedRemind.Core.Models.Prescription", "Prescription")
                        .WithMany("Medications")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedRemind.Core.Models.User", "User")
                        .WithMany("Medications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedRemind.Core.Models.Prescription", b =>
                {
                    b.HasOne("MedRemind.Core.Models.User", "User")
                        .WithMany("Prescriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedRemind.Core.Models.PrescriptionOCRResult", b =>
                {
                    b.HasOne("MedRemind.Core.Models.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MedRemind.Core.Models.Reminder", b =>
                {
                    b.HasOne("MedRemind.Core.Models.Medication", "Medication")
                        .WithMany("Reminders")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedRemind.Core.Models.VoiceRecording", "VoiceRecording")
                        .WithMany("Reminders")
                        .HasForeignKey("VoiceRecordingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Medication");

                    b.Navigation("VoiceRecording");
                });

            modelBuilder.Entity("MedRemind.Core.Models.VoiceRecording", b =>
                {
                    b.HasOne("MedRemind.Core.Models.User", "User")
                        .WithMany("VoiceRecordings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedRemind.Core.Models.Medication", b =>
                {
                    b.Navigation("DoseLogs");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("MedRemind.Core.Models.Prescription", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("MedRemind.Core.Models.User", b =>
                {
                    b.Navigation("Medications");

                    b.Navigation("Prescriptions");

                    b.Navigation("VoiceRecordings");
                });

            modelBuilder.Entity("MedRemind.Core.Models.VoiceRecording", b =>
                {
                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
