using System.Text.Json;
using System.Text.Json.Serialization;

namespace MedRemind.Core.DTOs;

/// <summary>
/// Comprehensive analysis report for prescription validation
/// Generated by the multi-agent validation system
/// </summary>
public class PrescriptionAnalysisReport
{
    [JsonPropertyName("reportId")]
    public string ReportId { get; set; } = Guid.NewGuid().ToString();

    [JsonPropertyName("prescriptionId")]
    public int? PrescriptionId { get; set; }

    [JsonPropertyName("prescriptionFileName")]
    public string? PrescriptionFileName { get; set; }

    [JsonPropertyName("generatedAt")]
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    [JsonPropertyName("ocrTextLength")]
    public int OcrTextLength { get; set; }

    [JsonPropertyName("parserResults")]
    public List<ParserAnalysis> ParserResults { get; set; } = new();

    [JsonPropertyName("crossValidation")]
    public CrossValidationResult CrossValidation { get; set; } = new();

    [JsonPropertyName("finalRecommendation")]
    public ValidationRecommendation FinalRecommendation { get; set; } = new();

    [JsonPropertyName("qualityMetrics")]
    public QualityMetrics QualityMetrics { get; set; } = new();

    [JsonPropertyName("issues")]
    public List<ValidationIssue> Issues { get; set; } = new();

    [JsonPropertyName("warnings")]
    public List<string> Warnings { get; set; } = new();

    [JsonPropertyName("processingTime")]
    public TimeSpan ProcessingTime { get; set; }
}

/// <summary>
/// Analysis of a single parser's result
/// </summary>
public class ParserAnalysis
{
    [JsonPropertyName("parserName")]
    public string ParserName { get; set; } = string.Empty;

    [JsonPropertyName("success")]
    public bool Success { get; set; }

    [JsonPropertyName("medicationCount")]
    public int MedicationCount { get; set; }

    [JsonPropertyName("hasPatientInfo")]
    public bool HasPatientInfo { get; set; }

    [JsonPropertyName("hasDoctorInfo")]
    public bool HasDoctorInfo { get; set; }

    [JsonPropertyName("hasPrescriptionDate")]
    public bool HasPrescriptionDate { get; set; }

    [JsonPropertyName("averageConfidence")]
    public double AverageConfidence { get; set; }

    [JsonPropertyName("completenessScore")]
    public double CompletenessScore { get; set; }

    [JsonPropertyName("processingTime")]
    public TimeSpan ProcessingTime { get; set; }

    [JsonPropertyName("errors")]
    public List<string> Errors { get; set; } = new();
}

/// <summary>
/// Cross-validation results comparing all parsers
/// </summary>
public class CrossValidationResult
{
    [JsonPropertyName("medicationConsistency")]
    public double MedicationConsistency { get; set; }

    [JsonPropertyName("patientNameMatch")]
    public bool PatientNameMatch { get; set; }

    [JsonPropertyName("doctorNameMatch")]
    public bool DoctorNameMatch { get; set; }

    [JsonPropertyName("dateConsistency")]
    public bool DateConsistency { get; set; }

    [JsonPropertyName("conflictingMedications")]
    public List<MedicationConflict> ConflictingMedications { get; set; } = new();

    [JsonPropertyName("consensusMedications")]
    public List<string> ConsensusMedications { get; set; } = new();

    [JsonPropertyName("overallAgreement")]
    public double OverallAgreement { get; set; }
}

/// <summary>
/// Final validation recommendation
/// </summary>
public class ValidationRecommendation
{
    [JsonPropertyName("status")]
    public ValidationStatus Status { get; set; }

    [JsonPropertyName("confidence")]
    public double Confidence { get; set; }

    [JsonPropertyName("recommendedParser")]
    public string? RecommendedParser { get; set; }

    [JsonPropertyName("requiresManualReview")]
    public bool RequiresManualReview { get; set; }

    [JsonPropertyName("reason")]
    public string? Reason { get; set; }

    [JsonPropertyName("suggestions")]
    public List<string> Suggestions { get; set; } = new();
}

/// <summary>
/// Quality metrics for the prescription
/// </summary>
public class QualityMetrics
{
    [JsonPropertyName("ocrQuality")]
    public double OcrQuality { get; set; }

    [JsonPropertyName("dataCompleteness")]
    public double DataCompleteness { get; set; }

    [JsonPropertyName("parserConsistency")]
    public double ParserConsistency { get; set; }

    [JsonPropertyName("overallQuality")]
    public double OverallQuality { get; set; }

    [JsonPropertyName("readabilityScore")]
    public double ReadabilityScore { get; set; }
}

/// <summary>
/// Validation issue found during analysis
/// </summary>
public class ValidationIssue
{
    [JsonPropertyName("severity")]
    public IssueSeverity Severity { get; set; }

    [JsonPropertyName("category")]
    public string Category { get; set; } = string.Empty;

    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    [JsonPropertyName("affectedParsers")]
    public List<string> AffectedParsers { get; set; } = new();

    [JsonPropertyName("recommendation")]
    public string? Recommendation { get; set; }
}

/// <summary>
/// Medication conflict between parsers
/// </summary>
public class MedicationConflict
{
    [JsonPropertyName("medicationName")]
    public string MedicationName { get; set; } = string.Empty;

    [JsonPropertyName("conflictType")]
    public string ConflictType { get; set; } = string.Empty;

    [JsonPropertyName("parserValues")]
    public Dictionary<string, string> ParserValues { get; set; } = new();

    [JsonPropertyName("suggestedResolution")]
    public string? SuggestedResolution { get; set; }
}

/// <summary>
/// Validation status
/// </summary>
public enum ValidationStatus
{
    Excellent,
    Good,
    Acceptable,
    NeedsReview,
    Failed
}

/// <summary>
/// Issue severity
/// </summary>
public enum IssueSeverity
{
    Low,
    Medium,
    High,
    Critical
}
